import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import MaxWithContainer from "@/components/MaxWithContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth select-none">
      <body className={`${inter.className} bg-black/90 text-white`}>
        <Header />
        <MaxWithContainer>{children}</MaxWithContainer>
      </body>
    </html>
  );
}
